# Azure Cosmos DB configuration (fill with real values in your environment)

azure.cosmos.uri= ${PET_STORE_ORDER_COSMO_URL}
azure.cosmos.key=${PET_STORE_ORDER_COSMO_KEY}
azure.cosmos.database=${PET_STORE_ORDER_DB_NAME}
# Order storage selection: IN_MEMORY or COSMOS
order.storage.type=${PET_STORE_STORAGE_TYPE}
# Azure Service Bus configuration
azure.servicebus.connection-string=${AZURE_SERVICEBUS_CONNECTION_STRING}
azure.servicebus.queue-name=${AZURE_SERVICEBUS_QUEUE_NAME}
